# Generated by Django 4.1.1 on 2022-09-25 00:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.CharField(choices=[('COMPANY', 'Company'), ('CUSTOMER', 'Customer'), ('admin', 'Admin')], default='admin', editable=False, max_length=50)),
                ('name', models.CharField(blank=True, default='Name', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, default='Phone', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(blank=True, default='Password', max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('work_type', models.CharField(choices=[('eCommerce', 'eCommerce'), ('TELECOM ', 'Telecom'), ('NGO', 'NGO'), ('MEDICAL', 'Medical'), ('FOOD DELIVERY', 'Food Delivery')], max_length=100)),
                ('country', models.CharField(blank=True, default='Iraq', max_length=50, null=True)),
                ('city', models.CharField(choices=[('BAGHDAD', 'Baghdad'), ('BASRAH', 'Basrah'), ('ARBIL', 'Arbil'), ('SULAYMANIYAH', 'Sulaymaniyah'), ('KARKH', 'Karkh'), ('KARBALA', 'Karbala'), ('NAJAF', 'Najaf'), ('RAMADI', 'Ramadi'), ('HILLAH', 'Hillah'), ('NASIRIYAH', 'Nasiriyah'), ('DUHOK', 'Duhok')], max_length=20)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, default='company_profile/default.png', null=True, upload_to='company_profile/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('skills', multiselectfield.db.fields.MultiSelectField(choices=[('Adaptability', 'Adaptability'), ('Execution_willingness', 'Execution willingness'), ('Resilience', 'Resilience'), ('Advice_ability', 'Advice ability'), ('Relationship_Management ', 'Relationship Management'), ('Charisma ', 'Charisma'), ('Discipline ', 'Discipline'), ('Decisiveness', 'Decisiveness'), ('Assertiveness', 'Assertiveness'), ('Flexibility', 'Flexibility'), ('Leadership', 'Leadership'), ('Holistic_thinking', 'Holistic thinking'), ('Patience', 'Patience'), ('Credibility', ' Credibility'), ('Helpfulness', ' Helpfulness'), ('Communication_skills', 'Communication skills'), ('Concept_Development', 'Concept Development'), ('Ability_to_cooperate', 'Ability to cooperate'), ('Creativity_Techniques', 'Creativity Techniques'), ('Customer_focus', 'Customer focus'), ('Logical_thinking', 'Logical thinking'), ('Solution_oriented', 'Solution oriented'), ('Organizational_capacity', 'Organizational capacity'), ('Personal_responsibility', 'Personal responsibility'), ('Time_Management', 'Time Management'), ('Teamwork', 'Teamwork'), ('Environmental_Awareness', 'Environmental Awareness'), ('Reliability', 'Reliability'), ('Tolerance', 'Tolerance')], max_length=255)),
                ('language', multiselectfield.db.fields.MultiSelectField(choices=[('Arabic', 'Arabic'), ('English', 'English'), ('Kurdish', 'Kurdish')], max_length=255)),
                ('job_title', models.CharField(choices=[('MARKETING SPECIALIST', 'Marketing Specialist'), ('MARKETING MANAGER', 'Marketing manager'), ('MARKETING DIRECTOR', 'Marketing Director'), ('GRAPHIC DESIGNER', 'Graphic Designer'), ('MARKETING RESEARCH ANALYST', 'Marketing Research Analyst'), ('MARKETING COMMUNICATIONS MANAGER', 'Marketing Communications Manager'), ('MARKETING CONSULTAN', 'Marketing Consultant'), ('PRODUCT MANAGER', 'Product Manager'), ('PUBLIC RELATIONS', 'Public Relations'), ('SOCIAL MEDIA ASSISTANT', 'Social Media Assistant'), ('BRAND MANAGER', 'Brand Manager'), ('SEO MANAGER', 'Seo Manager'), ('CONTENT MARKETING MANAGER', 'Content Marketing Manager'), ('MEDIA BUYER', 'Media Buyer'), ('DIGITAL MARKETING MANAGER', 'Digital Marketing Manager'), ('ECOMMERCE MARKETING SPECIALIST', 'Ecommerce Marketing Specialist'), ('BRAND STRATEGIST', 'Brand Strategist'), ('MEDIA RELATIONS COORDINATOR', 'Media Relations Coordinator'), ('IT PROFESSIONAL', 'IT Professional'), ('UX DESIGNER & UI DEVELOPER', 'UI Designer & UI Developer'), ('SQL DEVELOPER', 'SQL Developer'), ('WEB DESIGNER', 'Web Designer'), ('WEB DEVELOPER', 'Web Developer'), ('HELP DESK WORKER/DESKTOP SUPPORT', 'Help Desk Worker/desktop Support'), ('SOFTWARE ENGINEER', 'Software Engineer'), ('DATA ENTRY', 'Data Entry'), ('COMPUTER PROGRAMMER', 'Computer Programmer'), ('NETWORK ADMINISTRATOR', 'Network Administrator'), ('ARTIFICIAL INTELLIGENCE ENGINEER', 'Artificial Intelligence Engineer'), ('IT MANAGER', 'IT Manager'), ('TECHNICAL SPECIALIST', 'Technical Specialist'), ('APPLICATION DEVELOPER', 'Application Developer'), ('BACKEND DEVELOPER', 'Backend Developer'), ('FRONTEND DEVELOPER', 'Frontend Developer'), ('ADMINISTRATIVE ASSISTANT', 'Administrative Assistant'), ('RECEPTIONIST', 'Receptionist'), ('OFFICE MANAGER', 'Office Manager'), ('AUDITING CLERK', 'Auditing Clerk'), ('BOOKKEEPER', 'Bookkeeper'), ('ACCOUNT EXECUTIVE', 'Account Executive'), ('BRANCH MANAGER', 'Branch Manager'), ('BUSINESS MANAGER', 'Business Manager'), ('QUALITY CONTROL COORDINATOR', 'Quality Control Coordinator'), ('ADMINISTRATIVE MANAGER', 'Administrative Manager'), ('HUMAN RESOURCES', 'Human Resources'), ('OFFICE ASSISTANT', 'Office Assistant'), ('SECRETARY', 'Secretary'), ('ACCOUNT COLLECTOR', 'Account Collector')], max_length=100)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='customer_profile/')),
                ('cv', models.FileField(blank=True, default='default.pdf', null=True, upload_to='customer_profile/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(blank=True, choices=[('MARKETING SPECIALIST', 'Marketing Specialist'), ('MARKETING MANAGER', 'Marketing manager'), ('MARKETING DIRECTOR', 'Marketing Director'), ('GRAPHIC DESIGNER', 'Graphic Designer'), ('MARKETING RESEARCH ANALYST', 'Marketing Research Analyst'), ('MARKETING COMMUNICATIONS MANAGER', 'Marketing Communications Manager'), ('MARKETING CONSULTAN', 'Marketing Consultant'), ('PRODUCT MANAGER', 'Product Manager'), ('PUBLIC RELATIONS', 'Public Relations'), ('SOCIAL MEDIA ASSISTANT', 'Social Media Assistant'), ('BRAND MANAGER', 'Brand Manager'), ('SEO MANAGER', 'Seo Manager'), ('CONTENT MARKETING MANAGER', 'Content Marketing Manager'), ('MEDIA BUYER', 'Media Buyer'), ('DIGITAL MARKETING MANAGER', 'Digital Marketing Manager'), ('ECOMMERCE MARKETING SPECIALIST', 'Ecommerce Marketing Specialist'), ('BRAND STRATEGIST', 'Brand Strategist'), ('MEDIA RELATIONS COORDINATOR', 'Media Relations Coordinator'), ('IT PROFESSIONAL', 'IT Professional'), ('UX DESIGNER & UI DEVELOPER', 'UI Designer & UI Developer'), ('SQL DEVELOPER', 'SQL Developer'), ('WEB DESIGNER', 'Web Designer'), ('WEB DEVELOPER', 'Web Developer'), ('HELP DESK WORKER/DESKTOP SUPPORT', 'Help Desk Worker/desktop Support'), ('SOFTWARE ENGINEER', 'Software Engineer'), ('DATA ENTRY', 'Data Entry'), ('COMPUTER PROGRAMMER', 'Computer Programmer'), ('NETWORK ADMINISTRATOR', 'Network Administrator'), ('ARTIFICIAL INTELLIGENCE ENGINEER', 'Artificial Intelligence Engineer'), ('IT MANAGER', 'IT Manager'), ('TECHNICAL SPECIALIST', 'Technical Specialist'), ('APPLICATION DEVELOPER', 'Application Developer'), ('BACKEND DEVELOPER', 'Backend Developer'), ('FRONTEND DEVELOPER', 'Frontend Developer'), ('ADMINISTRATIVE ASSISTANT', 'Administrative Assistant'), ('RECEPTIONIST', 'Receptionist'), ('OFFICE MANAGER', 'Office Manager'), ('AUDITING CLERK', 'Auditing Clerk'), ('BOOKKEEPER', 'Bookkeeper'), ('ACCOUNT EXECUTIVE', 'Account Executive'), ('BRANCH MANAGER', 'Branch Manager'), ('BUSINESS MANAGER', 'Business Manager'), ('QUALITY CONTROL COORDINATOR', 'Quality Control Coordinator'), ('ADMINISTRATIVE MANAGER', 'Administrative Manager'), ('HUMAN RESOURCES', 'Human Resources'), ('OFFICE ASSISTANT', 'Office Assistant'), ('SECRETARY', 'Secretary'), ('ACCOUNT COLLECTOR', 'Account Collector')], max_length=100, null=True)),
                ('workplace', models.CharField(blank=True, choices=[('ON SITE', 'on site'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], max_length=30, null=True)),
                ('location', models.CharField(blank=True, choices=[('BAGHDAD', 'Baghdad'), ('BASRAH', 'Basrah'), ('ARBIL', 'Arbil'), ('SULAYMANIYAH', 'Sulaymaniyah'), ('KARKH', 'Karkh'), ('KARBALA', 'Karbala'), ('NAJAF', 'Najaf'), ('RAMADI', 'Ramadi'), ('HILLAH', 'Hillah'), ('NASIRIYAH', 'Nasiriyah'), ('DUHOK', 'Duhok')], max_length=40, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('FULL TIME', 'Full time'), ('PART TIME', 'Part time')], max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='cv.companyprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, default='Phone', max_length=50, null=True)),
                ('address', models.CharField(blank=True, default='Address', max_length=50, null=True)),
                ('country', models.CharField(blank=True, default='Iraq', max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cv.user',),
            managers=[
                ('Company', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, default='Phone', max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cv.user',),
            managers=[
                ('Customer', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(choices=[('MARKETING SPECIALIST', 'Marketing Specialist'), ('MARKETING MANAGER', 'Marketing manager'), ('MARKETING DIRECTOR', 'Marketing Director'), ('GRAPHIC DESIGNER', 'Graphic Designer'), ('MARKETING RESEARCH ANALYST', 'Marketing Research Analyst'), ('MARKETING COMMUNICATIONS MANAGER', 'Marketing Communications Manager'), ('MARKETING CONSULTAN', 'Marketing Consultant'), ('PRODUCT MANAGER', 'Product Manager'), ('PUBLIC RELATIONS', 'Public Relations'), ('SOCIAL MEDIA ASSISTANT', 'Social Media Assistant'), ('BRAND MANAGER', 'Brand Manager'), ('SEO MANAGER', 'Seo Manager'), ('CONTENT MARKETING MANAGER', 'Content Marketing Manager'), ('MEDIA BUYER', 'Media Buyer'), ('DIGITAL MARKETING MANAGER', 'Digital Marketing Manager'), ('ECOMMERCE MARKETING SPECIALIST', 'Ecommerce Marketing Specialist'), ('BRAND STRATEGIST', 'Brand Strategist'), ('MEDIA RELATIONS COORDINATOR', 'Media Relations Coordinator'), ('IT PROFESSIONAL', 'IT Professional'), ('UX DESIGNER & UI DEVELOPER', 'UI Designer & UI Developer'), ('SQL DEVELOPER', 'SQL Developer'), ('WEB DESIGNER', 'Web Designer'), ('WEB DEVELOPER', 'Web Developer'), ('HELP DESK WORKER/DESKTOP SUPPORT', 'Help Desk Worker/desktop Support'), ('SOFTWARE ENGINEER', 'Software Engineer'), ('DATA ENTRY', 'Data Entry'), ('COMPUTER PROGRAMMER', 'Computer Programmer'), ('NETWORK ADMINISTRATOR', 'Network Administrator'), ('ARTIFICIAL INTELLIGENCE ENGINEER', 'Artificial Intelligence Engineer'), ('IT MANAGER', 'IT Manager'), ('TECHNICAL SPECIALIST', 'Technical Specialist'), ('APPLICATION DEVELOPER', 'Application Developer'), ('BACKEND DEVELOPER', 'Backend Developer'), ('FRONTEND DEVELOPER', 'Frontend Developer'), ('ADMINISTRATIVE ASSISTANT', 'Administrative Assistant'), ('RECEPTIONIST', 'Receptionist'), ('OFFICE MANAGER', 'Office Manager'), ('AUDITING CLERK', 'Auditing Clerk'), ('BOOKKEEPER', 'Bookkeeper'), ('ACCOUNT EXECUTIVE', 'Account Executive'), ('BRANCH MANAGER', 'Branch Manager'), ('BUSINESS MANAGER', 'Business Manager'), ('QUALITY CONTROL COORDINATOR', 'Quality Control Coordinator'), ('ADMINISTRATIVE MANAGER', 'Administrative Manager'), ('HUMAN RESOURCES', 'Human Resources'), ('OFFICE ASSISTANT', 'Office Assistant'), ('SECRETARY', 'Secretary'), ('ACCOUNT COLLECTOR', 'Account Collector')], max_length=100)),
                ('company_worked_for', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='cv.customerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('LONG_LIST', 'Long List'), ('SHORT LIST', 'Short List'), ('ALL', 'All')], default='ALL', max_length=30)),
                ('why_apply', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application', to='cv.customerprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application', to='cv.job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='cv.customerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='saved_job',
            field=models.ManyToManyField(blank=True, related_name='job', to='cv.job'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='cv.customer'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='cv.company'),
        ),
    ]
