# Generated by Django 4.1.1 on 2022-10-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COMPANY', 'COMPANY'), ('CUSTOMER', 'CUSTOMER'), ('ADMIN', 'ADMIN')], default='ADMIN', editable=False, max_length=50),
        ),
    ]
