# Generated by Django 4.1.1 on 2022-10-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved')], default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved')], default='APPROVED', max_length=50),
        ),
    ]
