# Generated by Django 4.1.1 on 2022-09-25 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='cv',
            new_name='cv_url',
        ),
    ]
