# Generated by Django 4.1.1 on 2022-09-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='postion',
            new_name='position',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='company_profile/'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='Cv',
            field=models.FileField(blank=True, null=True, upload_to='customer_profile/'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='customer_profile/'),
        ),
    ]
