# Generated by Django 4.1.1 on 2022-10-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_alter_job_is_featured_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
