# Generated by Django 4.1.1 on 2022-09-11 20:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_rename_postion_job_position_companyprofile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='company_user',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='CompanyProfileImage',
            field=models.ImageField(blank=True, default='company_profile/default.png', null=True, upload_to='company_profile/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='Name',
            field=models.CharField(blank=True, default='Company Name', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='Name',
            field=models.CharField(blank=True, default='Customer', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='UserProfileImage',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='customer_profile/'),
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='JobImage',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='job/', verbose_name='Job Image'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='Cv',
            field=models.FileField(blank=True, default='default.pdf', null=True, upload_to='customer_profile/'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='saved_by',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='category',
            field=models.CharField(choices=[('LONG_LIST', 'Long List'), ('SHORT LIST', 'Short List')], default='LONG_LIST', max_length=30),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='job',
            name='saved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job', to='cv.customerprofile'),
        ),
    ]
