# Generated by Django 4.1.1 on 2022-10-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_job_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
