# Generated by Django 4.1.1 on 2022-09-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_companyprofile_user_alter_customerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='Name',
            field=models.CharField(blank=True, default='Company Name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='Name',
            field=models.CharField(blank=True, default='Customer', max_length=50, null=True),
        ),
    ]
