# Generated by Django 3.2 on 2022-09-14 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_alter_companyprofile_user_alter_customerprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cv.user')),
                ('phone', models.CharField(blank=True, default='Phone', max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cv.user',),
            managers=[
                ('Customer', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='CompanyProfile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='CustomerProfile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
