# Generated by Django 3.2 on 2022-09-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_alter_customerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
