# Generated by Django 3.2 on 2022-09-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_auto_20220915_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COMPANY', 'Company'), ('CUSTOMER', 'Customer'), ('admin', 'Admin')], default='admin', editable=False, max_length=50),
        ),
    ]
