# Generated by Django 3.2 on 2022-09-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_alter_companyprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, default='Address', max_length=50, null=True),
        ),
    ]
